# Generated by Django 2.2 on 2021-01-13 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages_work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_work', models.DateTimeField(auto_now_add=True)),
                ('end_work', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_duration', models.TimeField(auto_now=True)),
                ('package_work', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hours.Packages_work')),
            ],
        ),
    ]
