# Generated by Django 2.2 on 2021-01-11 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages_work',
            name='user',
        ),
    ]
