# Generated by Django 2.2 on 2021-01-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='start_work',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work_duration',
        ),
        migrations.AddField(
            model_name='work',
            name='work_type',
            field=models.BooleanField(default=True),
        ),
    ]
