# Generated by Django 2.2 on 2021-01-14 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_auto_20210114_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_type',
        ),
        migrations.AddField(
            model_name='work',
            name='start_work',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='work',
            name='work_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_work',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
