# Generated by Django 2.2 on 2021-01-12 23:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0002_remove_packages_work_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='end_work',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
