# Generated by Django 2.2 on 2021-01-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0003_auto_20210114_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_duration',
        ),
    ]
